#!/bin/bash
mkdir -p /root/alx-system_engineering-devops/0x00-shell_basics/welcome /root/alx-system_engineering-devops/0x00-shell_basics/welcome/to /root/alx-system_engineering-devops/0x00-shell_basics/welcome/to/school
